language: java
jdk:
  - oraclejdk8

sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer

jobs:
  include:
    - stage: build
      install: ./gradlew setupCiWorkspace
      script: ./gradlew build publish
    - stage: checkstyle
      install: echo "skipping default ./gradlew assemble"
      script: ./gradlew checkstyle
    - stage: build
      install: ./gradlew setupCiWorkspace
      script: ./gradlew -Dmod_version=snapshot build
      deploy:
        provider: pages
        local-dir: build/libs
        repo: afdw/TravisTest
        target-branch: master
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        on:
          branch: 8.0.x

env:
  global:
    TERM=dumb
